PostHog/Classes/Internal/PHGPostHogIntegration.m, PostHog/Classes/Internal/PHGPostHogUtils.h, PostHog/Classes/Internal/PHGPostHogUtils.m, PostHog/Classes/PHGPostHogConfiguration.h, PostHog/Classes/PHGPostHogConfiguration.m, PostHogTests/PostHogTests.swift
This is a backport from segmentio/analytics-ios (https://github.com/segmentio/analytics-ios/pull/892).
Any references to Apple's AdSupport framework might trip the App Store's static analysis, making it a bit unclear if SDK users can confidently say that their apps do not use the IDFA. By moving the responsibility to collect the IDFA out of the PostHog SDK and into the client app, the AdSupport references are gone and the question is easily answered.
It's a pretty small PR, but note that the PHGIDFA() function is gone and the caller of that function now checks for and calls a block provided as part of the SDK initialization.
With no changes to a client app, trigger an event, and verify …
=> Shift responsibility of IDFA collection to clients

CHANGELOG.md, PostHog.podspec, PostHog/Classes/Internal/PHGPostHogIntegration.m
According to issue #6, if you reference this old Apple ad framework in your code, your app won't be accepted to the app store. So this PR removes all references to it.
I pushed out version 1.2.0 with the change already as well.
=> Remove ad capturing

Package.swift
- Avoids generating a warning in a client's project when including the posthog-ios package
- Setup another Xcode project that uses the posthog-ios package and verify you don't see the warning about the Info.plist file
**Questions:**
=> Ignore Info.plist in the Swift Package

PostHog/Classes/PHGPostHogConfiguration.h, PostHog/Classes/PHGPostHogConfiguration.m, PostHog/Internal/PHGPostHogIntegration.m
Allows users of the library to opt out of sending a `$device_id` property by adding a `shouldSendDeviceID` to `PHGPostHogConfiguration`. The default value of this property is `YES` so there is no change to the standard behaviour.
`PHGPostHogConfiguration.h`
Create a `PHGPostHogConfiguration` and set `shouldSendDeviceID` to `NO`/`false` before using it to create/setup the PostHog client. Observe that when disabled, no `$device_id` property is seen.
I think it should be clear enough what I'm trying to do. Happy to rename if you have better suggestions (could be `disableDeviceID` perhaps).
N/A
**Screenshots …
=> Add shouldSendDeviceID to PHGPostHogConfiguration.

PostHog/Classes/PHGPostHog.h
Currently you can call `enable` or `disable` on `PHGPostHog` but there is no way to inspect whether the client is actually enabled or not. Rather than requiring library users to keep track of this themselves, this makes the `enabled` property public (but read only) so it is easy to inspect.
**Edit:** I do wonder if it might be worth renaming the getter on this property to `isEnabled` is it's more obviously distinct from the `enable` method, happy to do so if you think this would be worthwhile.
There's only 1 line changed :)
Create a client and then check the value after calling `enable`/`disable` on it.
N/A
**What are the relevant …
=> Make enabled property public (readonly).

PostHog/Classes/PHGPayloadManager.h, PostHog/Classes/PHGPayloadManager.m, PostHog/Classes/PHGPostHog.h, PostHog/Classes/PHGPostHog.m, PostHog/Internal/PHGPostHogIntegration.h, PostHog/Internal/PHGPostHogIntegration.m, PostHogTests/FeatureFlagTests.swift
=> Feat: Multivariate feature flags

PostHog/Classes/PHGPostHog.h, PostHog/Classes/PHGPostHog.m, PostHogTests/FeatureFlagTests.swift
- getFeatureFlag and isFeatureEnabled will accept `options`. send_event option will toggle sending of $feature_flag_called events
**Questions:**
=> Add option to getFeatureFlag and isFeatureEnabled

PostHog/Internal/PHGPostHogIntegration.m
`determineAppInstallationAttributionWithCompletionHandler` returns with warnings about usage of iOS private APIs and isn't really needed in general right now
=> Remove unnecessary adclient support

CHANGELOG.md, Examples/CarthageExample/CarthageExample/AppDelegate.swift, Examples/CocoapodsExample/CocoapodsExample/AppDelegate.m, Examples/ManualExample/ManualExample/AppDelegate.m, PostHog/Classes/PHGPostHog.m, PostHogTests/CapturingTests.swift, PostHogTests/EndToEndTests.swift, PostHogTests/FeatureFlagTests.swift, PostHogTests/MiddlewareTests.swift, PostHogTests/PostHogTests.swift
`isFeatureEnabled` should return `false` if feature flag is disabled
`PHGPostHog.m`
Demo project has one flag for each case, you can just call `isFeatureEnabled` with them.
Relates to https://github.com/PostHog/posthog-android/pull/42
**Questions:**
=> isFeatureEnabled now returns false if disabled

PostHog.xcodeproj/project.pbxproj, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogObjCExample.xcscheme, PostHog/PostHogConfig.swift, PostHog/PostHogExtensions.swift, PostHog/PostHogFeatureFlags.swift, PostHog/PostHogSDK.swift, PostHogExample/AppDelegate.swift, PostHogExample/ContentView.swift, PostHogObjCExample/AppDelegate.h, PostHogObjCExample/AppDelegate.m, PostHogObjCExample/Assets.xcassets/AccentColor.colorset/Contents.json, PostHogObjCExample/Assets.xcassets/AppIcon.appiconset/Contents.json, PostHogObjCExample/Assets.xcassets/Contents.json, PostHogObjCExample/Base.lproj/LaunchScreen.storyboard, PostHogObjCExample/Base.lproj/Main.storyboard, PostHogObjCExample/Info.plist, PostHogObjCExample/SceneDelegate.h, PostHogObjCExample/SceneDelegate.m, PostHogObjCExample/ViewController.h, PostHogObjCExample/ViewController.m, PostHogObjCExample/main.m
Add ObjC example and add method annotations
Otherwise ObjC calls would be super long and repetitive.
**Questions:**
=> Add ObjC example and add method annotations

PostHog.xcodeproj/project.pbxproj, PostHog/Models/PostHogEvent.swift, PostHog/PostHogApi.swift, PostHog/PostHogFileBackedQueue.swift, PostHog/PostHogLegacyQueue.swift, PostHog/PostHogQueue.swift, PostHog/PostHogStorage.swift, PostHog/Utils/DateUtils.swift, PostHogExample/AppDelegate.swift, PostHogTests/SessionManagerTest.swift
Compatibility with iOS SDK v2, move the old queue to the new queue and delete the old files
The iOS SDK previously didn't support multiple SDKs running at the same time since there's no `apiKey` or `tag` within the caching path (well they would share the same folder and it'd be a mess).
If we want to add support for it, we can make it in another PR, but I'd not block the first release because of that since there's no support already.
**Questions:**
- Do we need to update engineering / …
=> Compatibility with iOS SDK v2

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/maintainer-blank.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/build-examples.yml, .github/workflows/build.yml, .github/workflows/danger.yml, .github/workflows/lint.yml, .github/workflows/test.yml, dangerfile.js
=> GH Templates and codeowner

.github/workflows/release.yml, RELEASING.md, scripts/update-tag.sh
The GH release creates the tag before triggering the action, so the tag is pointed out to the code before the `bump-version.sh` changes which is OK for Cocoapods since the code is uploaded after the changes, but not ok for SPM since SPM depends on the tag.
This commit updates the tag after the `bump-version.sh` is executed.
The side effect was that someone using `3.0.0-alpha.3` would be reported as `$lib_version=3.0.0-alpha.2`.
Locally.
=> Fix release tag name

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHogExample/AppDelegate.swift, PostHogTests/PostHogSDKTest.swift
`Application Opened` event was being reported twice when opening for the first time.
The OS sends 2 notifications and we were calling the method in both of them
=> Do not report dupe `Application Opened` event during the first time

CHANGELOG.md, PostHog/PostHogContext.swift, PostHog/PostHogSDK.swift
Noticed a few properties were missing when doing https://github.com/PostHog/posthog-flutter/pull/76
Helps with better dashboard templates since you can filter out per device type
For another time:
Add better support for Mac Catalyst
Running the macOS example
=> chore: better macos support

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHog/PostHogStorage.swift, PostHogTests/PostHogSDKTest.swift
We would like to switch to PostHog, but the lack of session tracking on iOS was a dealbreaker. Although @marandaneto indicated it would be implemented this week in  #97 , I got curious after looking at the old PR.
This is still a draft PR. I would like feedback from @marandaneto if they would like me to continue to finish it (refine logic, add tests). Otherwise I'm happy for this to be closed and wait for the official thing.
Closes https://github.com/PostHog/posthog-ios/issues/97
Simply ran our app integrated with my local posthog-ios and saw that session ID appeared in the events, and I was able to track session related metrics https://us.posthog.com/shared/HeXYA1N8aHnvLpGfGrwpBzllJiswgw
I would like to add to the test suite if this PR is deemed workable.
=> Add session tracking

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHogExample/AppDelegate.swift, PostHogTests/PostHogSDKTest.swift
App opened event was being captured even though the lifecycle config was deactivated.
All the other events were already guarded by the lifecycle config.
=> fix: App opened event respects the life cycle config

CHANGELOG.md, PostHog/PostHogApi.swift, PostHog/PostHogQueue.swift, PostHog/PostHogSDK.swift, PostHogExample/AppDelegate.swift
https://github.com/PostHog/posthog-ios/issues/103
Running app with correct and wrong URLs
=> fix and improve logging if the `debug` flag is enabled

CHANGELOG.md, PostHog/Utils/DateUtils.swift
Closes https://github.com/PostHog/posthog-ios/issues/103
=> fix ISO8601 formatter to always use the 24h format

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHogTests/PostHogSDKTest.swift
Calling `reset` wasn't resetting the session.
=> fix reset session when reset or close are called

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog/PostHogContext.swift
Closes https://github.com/PostHog/posthog-ios/issues/92
both are always `xctest` because it comes from the test runner, test already exists.
=> chore: read `$app_name` from `CFBundleDisplayName` as a fallback if `CFBundleName` isn't available

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog/PrivacyInfo.xcprivacy
Closes https://github.com/PostHog/posthog-ios/issues/109
=> chore: add PrivacyInfo manifest

CHANGELOG.md, PostHog/PostHogApi.swift
follow up after the [incident](https://status.posthog.com/incidents/p9fhh5gnd5ky), not because of the iOS SDK but we don't want to hold the requests for too long anyway.
Android and [JS-lite](https://github.com/PostHog/posthog-js-lite/blob/c59c9d6b13bc972e0b1b3b66fe7a6c6a0e22f0ab/posthog-core/src/types.ts#L27-L28) are already 10s
=> chore: API requests do a 10s timeoutInterval instead of 60s

CHANGELOG.md, PostHog/PostHogQueue.swift, PostHogTests/PostHogQueueTest.swift
https://posthog.slack.com/archives/C0643MHR56X/p1710247917392199
similar to v3.2.3, I checked that no other config is missing from the last major version during merges and repo changes.
=> `maxQueueSize` wasn't respected when capturing events

PostHog.xcodeproj/project.pbxproj, PostHog/Replay/MethodSwizzler.swift, PostHog/Replay/NetworkSample.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/PostHogSessionReplayConfig.swift, PostHog/Replay/URLSessionInterceptor.swift, PostHog/Replay/URLSessionSwizzler.swift, PostHog/UIViewController.swift, PostHogExampleStoryboard/AppDelegate.swift, PostHogExampleStoryboard/ViewController.swift
example https://us.posthog.com/project/41706/replay/53D14CAB-D098-48E5-A995-A8670AE0FE3A
=> chore: recording network requests

PostHog.podspec
_#skip-changelog)
https://cocoapods.org/pods/PostHog
overview (readme) and changelog are outdated.
trusting https://stackoverflow.com/questions/76199890/how-to-update-pod-homepage-readme-on-cocoapods-org-website
=> fix: update changelog and readme on cocoapods for next release

.github/workflows/lint.yml
/bin/sh: swiftlint: command not found
make: *** [lint] Error 127
=> fix: missing swiftlint in GH Actions

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHogExampleStoryboard/SceneDelegate.swift, PostHogTests/PostHogSDKTest.swift
Similar https://github.com/PostHog/posthog-android/pull/139/
=> fix: rename groupProperties to groups for capture methods

CHANGELOG.md, PostHog/PostHogApi.swift, PostHog/PostHogQueue.swift, PostHog/PostHogSDK.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/PostHogSessionReplayConfig.swift, PostHog/Replay/RRWireframe.swift, PostHog/Replay/UIView+Util.swift, PostHog/Replay/ViewTreeSnapshotStatus.swift, PostHogExample/Api.swift, PostHogExample/AppDelegate.swift, PostHogExampleMacOS/AppDelegate.swift, PostHogExampleStoryboard/AppDelegate.swift, PostHogExampleTvOS/AppDelegate.swift, PostHogExampleWatchOS/PostHogExampleWatchOS Watch App/PostHogExampleWatchOSApp.swift, PostHogExampleWithPods/PostHogExampleWithPods/AppDelegate.swift, PostHogExampleWithSPM/PostHogExampleWithSPM/AppDelegate.swift, USAGE.md
=> chore: replay screenshot

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/PostHogSessionReplayConfig.swift, PostHogExample/AppDelegate.swift, USAGE.md
=> fix: screenshotMode typo

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog/Models/PostHogEvent.swift, PostHog/PostHogSDK.swift, PostHog/PostHogSessionManager.swift, PostHog/Utils/TimeBasedEpochGenerator.swift, PostHog/Utils/UUIDUtils.swift, PostHogTests/PostHogSessionManagerTest.swift, PostHogTests/UUIDTest.swift
Closes https://github.com/PostHog/posthog-ios/issues/144
Apple only has uuid v4
AFAIK there's no popular uuid v7 package for iOS
Inspired and adapted from https://github.com/nthState/UUIDV7/tree/main
Validated here https://uuidgenerator.dev/uuid-validator
=> chore: migrate UUID from v4 to v7

CHANGELOG.md, PostHog/PostHogQueue.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/UIView+Util.swift, PostHogExample/AppDelegate.swift, PostHogExample/ContentView.swift, PostHogExampleStoryboard/AppDelegate.swift, PostHogExampleStoryboard/ViewController.swift, USAGE.md
Tests running with masking enabled and disabled, with SwiftUI and UIKit
=> chore: screenshot masking

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog/Replay/CGSize+Util.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/UIView+Util.swift
customer report it:
> 51 iosApp                         0x2dd360 UIView.toImage() + 45 (UIView+Util.swift:45)
> 52 iosApp                         0x2d7480 PostHogReplayIntegration.toScreenshotWireframe(_:) + 239 (PostHogReplayIntegration.swift:239)
> 53 iosApp                         0x2d63c8 PostHogReplayIntegration.generateSnapshot(_:_:) + 80 (PostHogReplayIntegration.swift:80)
> 54 iosApp                         0x2d9324 PostHogReplayIntegration.snapshot() + 496 (PostHogReplayIntegration.swift:496)
> 55 iosApp                         0x2d9550 @objc PostHogReplayIntegration.snapshot() + 4342322512 (<compiler-generated>:4342322512)
similar to https://github.com/mapbox/mapbox-maps-ios/issues/1556
Running it but I can't reproduce the issue so I will release a version and check with the …
=> recording: fix MTLTextureDescriptor has width of zero issue

PostHog/Replay/UIView+Util.swift
`UIGraphicsBeginImageContextWithOptions` is deprecated, and we already use the `UIGraphicsImageRenderer` for downsizing.
=> chore: replace screenshot deprecated method

CHANGELOG.md, PostHog/PostHogSDK.swift
similar to https://github.com/PostHog/posthog-android/pull/166/files
supersede https://github.com/PostHog/posthog-ios/pull/165
=> chore: expose session id

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog/PostHogSDK.swift, PostHog/PostHogSessionManager.swift, PostHog/PostHogStorageManager.swift, PostHog/Utils/DateUtils.swift, PostHogTests/PostHogSDKTest.swift, PostHogTests/PostHogStorageManagerTest.swift
follow up https://github.com/PostHog/posthog-ios/pull/170/
Renamed PostHogSessionManager to PostHogStorageManager because it was more about reading/caching things from the storage.
Created a new PostHogSessionManager which is responsible for all session Id related
unit tests already exist and they are green, just refactoring and exposing the session id (setter) via an internal class instead of the public API
=> chore: expose session id setter

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHogTests/PostHogSDKTest.swift
similar to https://github.com/PostHog/posthog-android/pull/170
=> fix: do not clear events and reload flags after reset is called

CHANGELOG.md, PostHog/PostHogFeatureFlags.swift, PostHog/PostHogStorageManager.swift, PostHogExample/AppDelegate.swift, PostHogExample/ContentView.swift
Closes https://github.com/PostHog/posthog-ios/issues/176
Only read the value from the storage if it's not in memory yet.
Setters always overwrite the value in the storage and memory.
Storage only will be accessed the very first time unless the value changes async (eg flags), then the memory value is also updated.
This should reduce the main thread warnings.
All values are read and updated using lockers already.
unit tests already exist and they are all green
=> chore: cache flags, distinct id and anon id in memory to avoid file IO every time

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift
sometimes the recordings are black
one assumption is that the heuristics algo to detect the current window is wrong
this one uses the latest methods available from iOS 15 otherwise fallback to another one
running the app with storyboard and swiftui
=> recording: use non deprecated methods for getCurrentWindow if available

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog/PostHogSwiftUIViewModifiers.swift, PostHogExample/ContentView.swift, PostHogExample/PostHogExampleApp.swift
Spike for "semi automatic" or more UX friendly https://github.com/PostHog/posthog-ios/issues/167
Screen view (applied to the root view)
```swift
var body: some Scene {
WindowGroup {
ContentView()
.postHogScreenView() // will infer the class name (ContentView)
}
}
```
Widget view (applied to any view)
```swift
Button(action: triggerAction) {
Text("My Text!")
}.postHogViewSeen("My Button")
```
Events will be captured when the View triggers the [onAppear](https://developer.apple.com/documentation/swiftui/view/onappear(perform:)) method
=> chore: add SwiftUI View extensions to capture screen view and views in general (postHogViewSeen, postHogScreenView)

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHog/PostHogSessionManager.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHogTests/PostHogSDKTest.swift
The problem: If meta event is missing, the replay will be just a black screen because rrweb hides everything if no meta event is provided
We cache the window and the status object in a weak reference.
If the session rotates, and the window and status object are still in memory, we won't be sending the meta event again
Every time the session rotates, we clear the weak reference object so meta events will be sent again
Running
=> recording: send meta event again if session rotates

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift
I took another stab at https://github.com/PostHog/posthog-ios/issues/163, and https://github.com/PostHog/posthog-ios/issues/167, and could not find a way to do this.
SwiftUI compiles a Text into an Image of the very same type (and many other types), so it's not possible to know if its one or the other.
SwiftUI discards all the accessibility tags during compilation
Meanwhile, I found a bug and made a few improvements.
Running a sample app with each type
=> fix: mask swiftui picker if masking enabled

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHog/PostHogStorage.swift, PostHog/PostHogStorageManager.swift, PostHogExample/AppDelegate.swift, PostHogTests/PostHogFeatureFlagsTest.swift, PostHogTests/PostHogSDKTest.swift, PostHogTests/PostHogStorageManagerTest.swift
Closes https://github.com/PostHog/posthog-ios/issues/172
Closes https://github.com/PostHog/posthog-ios/issues/173
Needed for https://github.com/PostHog/posthog-ios/issues/185
=> chore: add is identified property

CHANGELOG.md, PostHog/PostHogContext.swift, PostHog/PostHogSDK.swift, PostHogTests/PostHogContextTest.swift
Closes https://github.com/PostHog/posthog-ios/issues/157
Relates to https://posthog.com/changelog/2024#android-sdk-now-sets-is-emulator-automatically
Running on both devices
=> chore: add Is Emulator support

CHANGELOG.md, PostHog/Replay/NetworkSample.swift, PostHog/Replay/URLSessionExtension.swift, PostHog/Replay/URLSessionInterceptor.swift
Relates to https://github.com/PostHog/posthog-android/pull/174
=> recording: network logs not counting the request transferSize but only the response transferSize

CHANGELOG.md, PostHog/Replay/CGSize+Util.swift, PostHog/Replay/URLSessionExtension.swift, PostHog/UIViewController.swift
follow up https://github.com/PostHog/posthog-ios/pull/189
=> fix: missing import for url session extensions

CHANGELOG.md, PostHog/PostHogSDK.swift
Those are just used internally but its better to guard it anyway
=> fix: missing is enabled checks

PostHog/PostHogFeatureFlags.swift
the endpoint is always /s/ so not a user facing change for now
running the example
=> fix: read session replay endpoint from cache

CHANGELOG.md, PostHog/PostHogConfig.swift
https://github.com/PostHog/posthog-react-native-session-replay/pull/2#discussion_r1765800338
=> fix: make snapshot endpoint api public but internal

CHANGELOG.md, PostHog/PostHogFeatureFlags.swift, PostHog/PostHogStorage.swift, PostHog/Replay/URLSessionInterceptor.swift, PostHogTests/PostHogFeatureFlagsTest.swift, PostHogTests/TestUtils/MockPostHogServer.swift
JS PR https://github.com/PostHog/posthog-js/pull/1040/
=> fix: session replay respect feature flag variants

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/UIView+Util.swift
Closes https://github.com/PostHog/posthog-js-lite/issues/292
Running multiple tests with multiple views/accesibility labels etc
=> recording: fix RN iOS masking

.periphery.yml, Makefile, PostHog/Models/PostHogEvent.swift, PostHog/PostHogFileBackedQueue.swift, PostHog/PostHogQueue.swift, PostHog/PostHogSDK.swift, PostHog/PostHogStorage.swift, PostHog/Utils/Errors.swift, PostHog/Utils/Reachability.swift
=> fix: remove some unused code and add periphery api

CHANGELOG.md, PostHog/PostHogSDK.swift, PostHog/PostHogSessionManager.swift, PostHog/PostHogVersion.swift
Relates to https://github.com/PostHog/posthog-js-lite/pull/307/files
=> recording: do not rotate the session id for hybrid SDKs

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/UIView+Util.swift, PostHog/Utils/UIApplication+.swift
Closes #231 
This issue was a bit challenging to uncover, but the solution turned out to be quite straightforward. After digging into the frontend code, I realized we always use `position: fixed` when styling nodes. To ensure the wireframe renders correctly, we need to convert all view frames to global screen coordinates.
Locally with some sample projects
=> fix: use global frame on wireframe views

CHANGELOG.md, PostHog/App Life Cycle/PostHogAppLifeCycleIntegration.swift, PostHog/PostHogConfig.swift, PostHog/PostHogRemoteConfig.swift, PostHog/PostHogSDK.swift, PostHog/PostHogStorage.swift, PostHogExample/ContentView.swift, PostHogTests/PostHogFeatureFlagsTest.swift, PostHogTests/PostHogFeatureFlagsV3Test.swift, PostHogTests/PostHogRemoteConfigTest.swift, PostHogTests/PostHogSDKTest.swift
This is a follow-up to #373 (and targets that branch)
Feature flags that rely on person properties like `$app_version` or `$os_version` often fail to work immediately after SDK initialization because these properties aren't available until `identify()` calls are processed server-side. This creates a race condition where flags return incorrect values during the critical first moments of app usage.
This PR implements automatic person properties similar to the PostHog web SDK, where common device and app properties are automatically set as person properties during SDK initialization.
**Properties automatically set:**
- `$app_version` - App version from bundle
(`CFBundleShortVersionString`)
- `$app_build` - App build number (`CFBundleVersion`)
- `$os_name` - Operating system name (iOS, macOS, …
=> feat: Support default properties
