CHANGELOG.md, PostHog.podspec, PostHog/Classes/Internal/PHGPostHogIntegration.m, PostHog/Classes/PHGPostHogConfiguration.h, PostHog/Classes/PHGPostHogConfiguration.m, PostHogTests/PostHogTests.swift
No need for config params if they do nothing.
=> Also remove enableAdvertisingCapturing and adSupportBlock

.github/workflows/tests.yml
Adds a workflow for automated tests
Let's just see if it works...
=> feat: Github actions tests

PostHog/Classes/PHGPayloadManager.m, PostHog/Internal/PHGPostHogIntegration.h, PostHog/Internal/PHGPostHogIntegration.m
=> Persistence of feature flags and groups

PostHog/Classes/PHGPayloadManager.m
- addresses https://github.com/PostHog/posthog-ios/issues/35
**Questions:**
=> fix: Allow for optional setting of key values

PostHog/Classes/PHGPayloadManager.h, PostHog/Classes/PHGPayloadManager.m, PostHog/Classes/PHGPostHog.h, PostHog/Classes/PHGPostHog.m, PostHog/Internal/PHGPostHogIntegration.h, PostHog/Internal/PHGPostHogIntegration.m, PostHogTests/FeatureFlagTests.swift
- https://github.com/PostHog/posthog/issues/13627
- Extends the spec here: getFeatureFlag<type>Payload so that the return will be typed as expected
**Questions:**
=> feat: feature flag payloads support

PostHog/Classes/PHGPayloadManager.m, PostHog/Internal/PHGHTTPClient.m, PostHogTests/FeatureFlagTests.swift
- resiliency points for https://github.com/PostHog/posthog/issues/13627
**Questions:**
=> chore: feature flag resiliency

PostHog/Classes/PHGPostHog.m
Updates the version number to current. Fixes https://github.com/PostHog/posthog-ios/issues/41
🤷‍♀️  Not sure if this needs testing
https://github.com/PostHog/posthog-ios/issues/41
**Questions:**
=> fix: update version number

.github/workflows/release.yml, RELEASING.md, scripts/commit-code.sh, scripts/create-tag.sh, scripts/prepare-release.sh
Same as https://github.com/PostHog/posthog-android/pull/63
=> Fix Release as a non-Draft and manually create a tag before release

PostHog/PostHogSDK.swift
=> fix: api key logging during sdk init

PostHog/PostHogApi.swift, PostHog/PostHogContext.swift, PostHog/PostHogVersion.swift
Required for https://github.com/PostHog/posthog-flutter/issues/59
=> chore: Expose sdk name and version to be set on Flutter

PostHog.xcodeproj/project.pbxproj, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleStoryboard.xcscheme, PostHog/PostHogConfig.swift, PostHog/PostHogFeatureFlags.swift, PostHog/PostHogSDK.swift, PostHog/Replay/CGColor+Util.swift, PostHog/Replay/Date+Util.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/PostHogSessionReplayConfig.swift, PostHog/Replay/RRStyle.swift, PostHog/Replay/RRWireframe.swift, PostHog/Replay/String+Util.swift, PostHog/Replay/UIColor+Util.swift, PostHog/Replay/UITextInputTraits+Util.swift, PostHog/Replay/UIView+Util.swift, PostHog/Replay/ViewLayoutTracker.swift, PostHogExampleStoryboard/AppDelegate.swift, PostHogExampleStoryboard/Assets.xcassets/AccentColor.colorset/Contents.json, PostHogExampleStoryboard/Assets.xcassets/AppIcon.appiconset/Contents.json, PostHogExampleStoryboard/Assets.xcassets/Contents.json, PostHogExampleStoryboard/Base.lproj/LaunchScreen.storyboard, PostHogExampleStoryboard/Base.lproj/Main.storyboard, PostHogExampleStoryboard/Info.plist, PostHogExampleStoryboard/SceneDelegate.swift, PostHogExampleStoryboard/ViewController.swift
=> chore: recording masking

PostHog/Replay/PostHogReplayIntegration.swift
=> chore: swiftui not supported for recording

PostHog.xcodeproj/project.pbxproj, PostHog/PostHogSwizzler.swift, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/UIApplicationTracker.swift, PostHog/Replay/ViewLayoutTracker.swift, PostHog/UIViewController.swift, PostHogExampleStoryboard/AppDelegate.swift, PostHogExampleStoryboard/ViewController.swift
=> chore: touch events

.github/workflows/lint.yml, CHANGELOG.md, PostHog/PostHogSDK.swift, PostHog/PostHogStorage.swift, PostHogExample/AppDelegate.swift, PostHogTests/PostHogSDKTest.swift
merge https://github.com/PostHog/posthog-ios/tree/3.2.5_patch back to main
=> chore: merge patch into main

CHANGELOG.md, PostHog.podspec
Tries to fix https://github.com/PostHog/posthog-ios/issues/137
=> fix: PrivacyInfo warning when using Cocoapods

CHANGELOG.md, PostHog/PostHogConfig.swift
similar https://github.com/PostHog/posthog-android/pull/137
=> chore: change host to new address

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift
* only mask if there's any content (text, image)
* added missing components that are placeholders for wireframes but not for screenshots
=> recording: improvements to screenshot masking

CHANGELOG.md, PostHog.xcodeproj/project.pbxproj, PostHog.xcodeproj/xcshareddata/xcschemes/PostHog.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExample.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleMacOS.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleStoryboard.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleTvOS.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleWatchOS Watch App.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleWithPods.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogExampleWithSPM.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogObjCExample.xcscheme, PostHog.xcodeproj/xcshareddata/xcschemes/PostHogTests.xcscheme, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/PostHogSessionReplayConfig.swift, PostHog/Replay/RRWireframe.swift, PostHog/Replay/UIApplicationTracker.swift
=> fix: screenshot background processing

CHANGELOG.md, PostHog/Replay/PostHogReplayIntegration.swift, PostHog/Replay/PostHogSessionReplayConfig.swift, PostHog/Replay/UIView+Util.swift
https://github.com/PostHog/posthog-ios/issues/151#issuecomment-2289415555
I am testing directly on this sample app and feels much better
=> chore: more performance improvements

PostHog/PostHogContext.swift, PostHog/PostHogSDK.swift, PostHogExample/AppDelegate.swift, PostHogTests/PostHogContextTest.swift
Relates to https://github.com/PostHog/posthog-android/pull/172
_#skip-changelog_ since its not a user facing change
Capturing both type of events
=> chore: recordings sdk info

PostHogExampleWithSPM/PostHogExampleWithSPM.xcodeproj/project.pbxproj
=> fix: spm example already depends locally, no need of a remote dep

PostHog/PostHogSDK.swift, PostHog/PostHogSessionManager.swift
https://github.com/PostHog/posthog-react-native-session-replay depends on it
=> fix: rn session replay class visibility objc

CHANGELOG.md, PostHog/PostHogConfig.swift, PostHog/PostHogSDK.swift, PostHog/PostHogStorageManager.swift, PostHogExample/AppDelegate.swift
required for https://github.com/PostHog/posthog-js-lite/pull/269
=> chore: make storage manager public to the rn sdk

Makefile, PostHog/PostHogSDK.swift, PostHogTests/PostHogSDKTest.swift
https://posthog.slack.com/archives/C03PB072FMJ/p1730970776839319?thread_ts=1730881816.333539&cid=C03PB072FMJ
=> fix: flaky tests when adding groupds and reloading flags
